// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBig2vcd0-cGGEmqyM-nR6rnL7KCe7FR0Q',
    appId: '1:427798624482:web:df28d1e021da934fe906bb',
    messagingSenderId: '427798624482',
    projectId: 'mealfatigue',
    authDomain: 'mealfatigue.firebaseapp.com',
    storageBucket: 'mealfatigue.firebasestorage.app',
    measurementId: 'G-MG4N0YXJZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhlp07OEV7-3YQcjzCPPZzB5L8Dbq80Q',
    appId: '1:427798624482:android:8c0cb28621308e60e906bb',
    messagingSenderId: '427798624482',
    projectId: 'mealfatigue',
    storageBucket: 'mealfatigue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmHRdGiyHcKLQlk-qJAk3eCEKC2247t54',
    appId: '1:427798624482:ios:40993345d6130ecee906bb',
    messagingSenderId: '427798624482',
    projectId: 'mealfatigue',
    storageBucket: 'mealfatigue.firebasestorage.app',
    iosBundleId: 'com.example.mealfatigue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmHRdGiyHcKLQlk-qJAk3eCEKC2247t54',
    appId: '1:427798624482:ios:40993345d6130ecee906bb',
    messagingSenderId: '427798624482',
    projectId: 'mealfatigue',
    storageBucket: 'mealfatigue.firebasestorage.app',
    iosBundleId: 'com.example.mealfatigue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBig2vcd0-cGGEmqyM-nR6rnL7KCe7FR0Q',
    appId: '1:427798624482:web:e3c26e996431ff33e906bb',
    messagingSenderId: '427798624482',
    projectId: 'mealfatigue',
    authDomain: 'mealfatigue.firebaseapp.com',
    storageBucket: 'mealfatigue.firebasestorage.app',
    measurementId: 'G-QY7YTK827N',
  );
}
